// frontend/app/forum/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { api, getToken, type ForumTopic, type PostItem } from '@/lib/api';
import PostReplies from '@/components/PostReplies';

function timeLabel(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '';
  return d.toLocaleString('zh-CN', { hour12: false }).replace(/:\d{2}$/, '');
}

export default function ForumPage() {
  const [topics, setTopics] = useState<ForumTopic[]>([]);
  const [activeTopic, setActiveTopic] = useState('');
  const [posts, setPosts] = useState<PostItem[]>([]);
  const [draft, setDraft] = useState('');
  const [draftTopic, setDraftTopic] = useState('');
  const [err, setErr] = useState('');
  const [loading, setLoading] = useState(true);
  const [posting, setPosting] = useState(false);
  const loggedIn = Boolean(getToken());

  useEffect(() => {
    Promise.all([api.forumTopics(), api.posts()])
      .then(([ts, r]) => {
        setTopics(ts);
        setDraftTopic(ts[0]?.id ?? '');
        setPosts(r.items);
      })
      .catch((e) => setErr((e as Error).message))
      .finally(() => setLoading(false));
  }, []);

  async function selectTopic(topicId: string) {
    setActiveTopic(topicId);
    setErr('');
    try {
      const r = await api.posts(topicId ? { topicId } : {});
      setPosts(r.items);
    } catch (e) {
      setErr((e as Error).message);
    }
  }

  async function submit() {
    if (!getToken()) {
      window.location.href = '/login';
      return;
    }
    const content = draft.trim();
    if (!content) return;
    if (!draftTopic) {
      setErr('请选择主题');
      return;
    }
    setErr('');
    setPosting(true);
    try {
      const p = await api.createPost(content, draftTopic);
      if (!activeTopic || activeTopic === draftTopic) setPosts((list) => [p, ...list]);
      setDraft('');
    } catch (e) {
      setErr((e as Error).message);
    } finally {
      setPosting(false);
    }
  }

  const topicName = (id: string | null) => topics.find((t) => t.id === id)?.name ?? '';

  if (loading) {
    return <main className="flex min-h-screen items-center justify-center text-ink/50">加载中...</main>;
  }

  return (
    <main className="mx-auto max-w-3xl px-6 py-10">
      <a href="/" className="text-sm font-bold text-ink hover:text-sky">
        返回首页
      </a>
      <h1 className="mb-1 mt-1 text-3xl font-semibold tracking-tight text-ink">交流</h1>
      <p className="mb-6 text-sm text-ink/55">发帖提问、分享经验,与同行讨论交流。</p>

      <div className="mb-6 flex flex-wrap gap-2">
        <button
          onClick={() => selectTopic('')}
          className={`rounded-full px-4 py-1.5 text-sm font-medium transition ${
            activeTopic === '' ? 'bg-steel text-white' : 'bg-white/60 text-ink/60 hover:text-ink'
          }`}
        >
          全部
        </button>
        {topics.map((topic) => (
          <button
            key={topic.id}
            onClick={() => selectTopic(topic.id)}
            className={`rounded-full px-4 py-1.5 text-sm font-medium transition ${
              activeTopic === topic.id ? 'bg-steel text-white' : 'bg-white/60 text-ink/60 hover:text-ink'
            }`}
          >
            {topic.name}
          </button>
        ))}
      </div>

      <section className="mb-8 rounded-2xl bg-white/60 p-5 shadow-sm ring-1 ring-white/55 backdrop-blur-xl">
        {loggedIn ? (
          <>
            <textarea
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              placeholder="说点什么..."
              rows={3}
              maxLength={1000}
              className="w-full resize-none rounded-lg border border-ink/15 px-3 py-2 text-sm outline-none focus:border-sky focus:ring-2 focus:ring-sky/20"
            />
            <div className="mt-3 flex items-center justify-between gap-3">
              <div className="flex items-center gap-2">
                <span className="text-xs text-ink/40">{draft.length}/1000</span>
                <select
                  value={draftTopic}
                  onChange={(e) => setDraftTopic(e.target.value)}
                  className="rounded-lg border border-ink/15 px-2 py-1 text-sm outline-none focus:border-sky"
                >
                  {topics.length === 0 && <option value="">(暂无主题)</option>}
                  {topics.map((topic) => (
                    <option key={topic.id} value={topic.id}>
                      {topic.name}
                    </option>
                  ))}
                </select>
              </div>
              <button
                onClick={submit}
                disabled={posting || !draft.trim() || !draftTopic}
                className="rounded-lg bg-sky px-5 py-2 text-sm font-medium text-white hover:bg-steel disabled:opacity-50"
              >
                发布
              </button>
            </div>
          </>
        ) : (
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <p className="text-sm text-ink/55">未登录可以查看交流内容。登录后可以发帖和评论。</p>
            <a href="/login" className="rounded-lg bg-steel px-5 py-2 text-center text-sm font-medium text-white hover:bg-ink">
              登录后发言
            </a>
          </div>
        )}
      </section>

      {err && <p className="mb-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-600">{err}</p>}
      {posts.length === 0 && !err && (
        <p className="rounded-2xl bg-white/60 p-8 text-center text-ink/50 shadow-sm ring-1 ring-white/55 backdrop-blur-xl">
          还没有帖子。
        </p>
      )}

      <div className="space-y-4">
        {posts.map((post) => (
          <PostCard
            key={post.id}
            post={post}
            topicName={topicName(post.topicId)}
            showTopic={!activeTopic}
            loggedIn={loggedIn}
          />
        ))}
      </div>
    </main>
  );
}

function PostCard({
  post,
  topicName,
  showTopic,
  loggedIn,
}: {
  post: PostItem;
  topicName: string;
  showTopic: boolean;
  loggedIn: boolean;
}) {
  const [open, setOpen] = useState(false);
  const [replyCount, setReplyCount] = useState(post.replyCount);

  return (
    <section className="rounded-2xl bg-white/60 p-6 shadow-sm ring-1 ring-white/55 backdrop-blur-xl">
      <div className="mb-2 flex items-center gap-2 text-xs text-ink/45">
        <span className="font-medium text-ink/70">{post.nickname}</span>
        {showTopic && topicName && <span className="rounded-md bg-sky/10 px-2 py-0.5 text-sky">{topicName}</span>}
        <span>{timeLabel(post.createdAt)}</span>
      </div>
      <p className="whitespace-pre-wrap text-ink/85">{post.content}</p>
      <button onClick={() => setOpen((value) => !value)} className="mt-3 text-sm text-ink/50 hover:text-ink">
        {open ? '收起回复' : `回复${replyCount ? ` (${replyCount})` : ''}`}
      </button>
      {open && <PostReplies postId={post.id} canReply={loggedIn} onCountChange={setReplyCount} />}
    </section>
  );
}

// apps/student-uni/src/pages/forum/index.vue
<script setup lang="ts">
import { onShow } from '@dcloudio/uni-app';
import { ref } from 'vue';
import { api, requireLogin, type ForumTopic, type PostItem } from '@/utils/api';

const topics = ref<ForumTopic[]>([]);
const posts = ref<PostItem[]>([]);
const activeTopic = ref('');
const draftTopic = ref('');
const draft = ref('');
const loading = ref(false);
const posting = ref(false);

function toast(message: string) {
  uni.showToast({ title: message, icon: 'none' });
}

function timeLabel(iso: string) {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '';
  return `${d.getMonth() + 1}-${d.getDate()} ${String(d.getHours()).padStart(2, '0')}:${String(
    d.getMinutes(),
  ).padStart(2, '0')}`;
}

function topicName(id: string | null) {
  return topics.value.find((t) => t.id === id)?.name || '';
}

async function load(topicId = activeTopic.value) {
  if (!requireLogin()) return;
  loading.value = true;
  try {
    const [topicRows, postRows] = await Promise.all([api.forumTopics(), api.posts(topicId ? { topicId } : {})]);
    topics.value = topicRows;
    posts.value = postRows.items;
    if (!draftTopic.value) draftTopic.value = topicRows[0]?.id || '';
  } catch (e) {
    toast((e as Error).message);
  } finally {
    loading.value = false;
  }
}

async function selectTopic(topicId: string) {
  activeTopic.value = topicId;
  await load(topicId);
}

async function submit() {
  const content = draft.value.trim();
  if (!content) return;
  if (!draftTopic.value) {
    toast('请选择主题');
    return;
  }
  posting.value = true;
  try {
    const created = await api.createPost(content, draftTopic.value);
    if (!activeTopic.value || activeTopic.value === draftTopic.value) {
      posts.value = [created, ...posts.value];
    }
    draft.value = '';
  } catch (e) {
    toast((e as Error).message);
  } finally {
    posting.value = false;
  }
}

onShow(() => load());
</script>

<template>
  <view class="page forum-page">
    <view class="header">
      <text class="title">交流</text>
      <text class="subtitle">发帖提问、分享经验，与同行讨论交流。</text>
    </view>

    <scroll-view scroll-x class="topics" show-scrollbar="false">
      <view class="topic-row">
        <view :class="['topic-chip', activeTopic === '' && 'active']" @tap="selectTopic('')">全部</view>
        <view
          v-for="topic in topics"
          :key="topic.id"
          :class="['topic-chip', activeTopic === topic.id && 'active']"
          @tap="selectTopic(topic.id)"
        >
          {{ topic.name }}
        </view>
      </view>
    </scroll-view>

    <view class="card composer">
      <textarea v-model="draft" class="textarea" maxlength="1000" placeholder="说点什么..." />
      <view class="composer-footer">
        <picker
          mode="selector"
          :range="topics"
          range-key="name"
          @change="(e) => (draftTopic = topics[Number(e.detail.value)]?.id || '')"
        >
          <text class="topic-select">{{ topicName(draftTopic) || '选择主题' }}</text>
        </picker>
        <button class="btn post-btn" :loading="posting" :disabled="!draft.trim() || !draftTopic" @tap="submit">
          发布
        </button>
      </view>
    </view>

    <view v-if="loading" class="empty">加载中...</view>
    <view v-else-if="posts.length === 0" class="empty">还没有帖子，来发第一条吧。</view>

    <view class="post-list">
      <view v-for="post in posts" :key="post.id" class="card post-card">
        <view class="post-meta">
          <text class="author">{{ post.nickname }}</text>
          <text v-if="topicName(post.topicId)" class="badge">{{ topicName(post.topicId) }}</text>
          <text>{{ timeLabel(post.createdAt) }}</text>
        </view>
        <text class="post-content">{{ post.content }}</text>
        <text class="reply-count">回复 {{ post.replyCount }}</text>
      </view>
    </view>
  </view>
</template>

<style scoped lang="scss">
.forum-page {
  display: flex;
  flex-direction: column;
  gap: 28rpx;
}

.header {
  display: flex;
  flex-direction: column;
  gap: 14rpx;
  padding-top: 16rpx;
}

.topics {
  white-space: nowrap;
}

.topic-row {
  display: flex;
  gap: 16rpx;
}

.topic-chip {
  background: rgba(255, 255, 255, 0.72);
  border-radius: 999rpx;
  color: rgba(17, 24, 39, 0.58);
  display: inline-flex;
  font-size: 26rpx;
  font-weight: 700;
  padding: 16rpx 28rpx;
}

.topic-chip.active {
  background: #38577a;
  color: #fff;
}

.composer {
  display: flex;
  flex-direction: column;
  gap: 20rpx;
}

.composer-footer {
  align-items: center;
  display: flex;
  justify-content: space-between;
  gap: 20rpx;
}

.topic-select {
  color: rgba(17, 24, 39, 0.62);
  font-size: 26rpx;
}

.post-btn {
  min-height: 72rpx;
  min-width: 160rpx;
}

.empty {
  color: rgba(17, 24, 39, 0.45);
  font-size: 28rpx;
  padding: 48rpx 0;
  text-align: center;
}

.post-list {
  display: flex;
  flex-direction: column;
  gap: 22rpx;
}

.post-card {
  display: flex;
  flex-direction: column;
  gap: 16rpx;
}

.post-meta {
  align-items: center;
  color: rgba(17, 24, 39, 0.42);
  display: flex;
  flex-wrap: wrap;
  font-size: 24rpx;
  gap: 12rpx;
}

.author {
  color: rgba(17, 24, 39, 0.78);
  font-weight: 700;
}

.badge {
  background: rgba(31, 111, 235, 0.1);
  border-radius: 8rpx;
  color: #1f6feb;
  padding: 4rpx 10rpx;
}

.post-content {
  color: rgba(17, 24, 39, 0.86);
  font-size: 30rpx;
  line-height: 1.7;
  white-space: pre-wrap;
}

.reply-count {
  color: rgba(17, 24, 39, 0.48);
  font-size: 24rpx;
}
</style>
