// frontend/app/study/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { api, assetUrl, getToken, type QuestionItem } from '@/lib/api';
import Comments from '@/components/Comments';

const PAGE_SIZES = [20];

export default function StudyPage() {
  const router = useRouter();
  const [items, setItems] = useState<QuestionItem[]>([]);
  const [categories, setCategories] = useState<string[]>([]);
  const [category, setCategory] = useState('');
  const [keyword, setKeyword] = useState(''); // 搜索输入(即时)
  const [searchKw, setSearchKw] = useState(''); // 防抖后真正用于查询的关键词
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const [jumpTo, setJumpTo] = useState('1');
  const [total, setTotal] = useState(0);
  const [err, setErr] = useState('');
  const [loading, setLoading] = useState(true);

  // 搜索防抖 350ms,避免每个字符都打接口。
  useEffect(() => {
    const t = setTimeout(() => setSearchKw(keyword.trim()), 350);
    return () => clearTimeout(t);
  }, [keyword]);

  // 科目枚举加载后,默认选中第一个科目(去掉"全部科目"聚合项)。
  useEffect(() => {
    if (!getToken()) {
      router.push('/login');
      return;
    }
    api
      .categories()
      .then((cs) => {
        setCategories(cs);
        if (cs.length) setCategory((cur) => cur || cs[0]);
      })
      .catch(() => undefined);
  }, [router]);

  // 切换科目/每页条数/搜索词时回到第 1 页。
  useEffect(() => {
    setPage(1);
  }, [category, pageSize, searchKw]);

  useEffect(() => {
    if (!getToken() || !category) return;
    setLoading(true);
    api
      .questions({ usage: 'study', category, keyword: searchKw || undefined, page, pageSize })
      .then((r) => {
        setItems(r.items);
        setTotal(r.total);
        setPage(r.page);
        setPageSize(r.pageSize);
      })
      .catch((e) => setErr((e as Error).message))
      .finally(() => setLoading(false));
  }, [category, searchKw, page, pageSize]);

  const totalPages = Math.max(1, Math.ceil(total / pageSize));

  useEffect(() => {
    setJumpTo(String(page));
  }, [page]);

  function commitJump() {
    const next = Math.min(totalPages, Math.max(1, Number(jumpTo) || 1));
    setPage(next);
    setJumpTo(String(next));
  }

  return (
    <main className="mx-auto max-w-5xl px-6 py-10">
      <a href="/" className="text-sm font-bold text-ink hover:text-sky">
        ← 返回首页
      </a>
      <h1 className="mb-4 mt-1 text-3xl font-semibold tracking-tight text-ink">专题学习</h1>

      <div className="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-2">
        <section className="rounded-2xl border border-sky/30 bg-sky/10 p-4">
          <p className="text-base font-semibold text-ink">顺序学习</p>
          <p className="mt-1 text-sm text-ink/55">按科目顺序刷题,答错后进入错题本。</p>
        </section>
        <a
          href="/exam"
          className="rounded-2xl bg-white/60 p-4 shadow-sm ring-1 ring-white/55 transition hover:-translate-y-0.5 hover:ring-sky/30"
        >
          <p className="text-base font-semibold text-ink">模拟考试</p>
          <p className="mt-1 text-sm text-ink/55">进入模拟考试,开始考试部分保持不变。</p>
        </a>
      </div>

      <div className="flex flex-col gap-6 sm:flex-row">
        {/* 左侧顺序轴:垂直科目导航,点击切换 */}
        <nav className="sm:sticky sm:top-10 sm:h-fit sm:w-52 sm:shrink-0">
          <ul className="flex gap-2 overflow-x-auto pb-2 sm:flex-col sm:gap-1 sm:overflow-visible sm:pb-0">
            {categories.map((c) => {
              const active = c === category;
              return (
                <li key={c} className="shrink-0">
                  <button
                    onClick={() => setCategory(c)}
                    className={`w-full whitespace-nowrap rounded-lg border-l-2 px-3 py-2 text-left text-sm transition sm:whitespace-normal ${
                      active
                        ? 'border-sky bg-sky/10 font-semibold text-ink'
                        : 'border-transparent text-ink/55 hover:bg-mist hover:text-ink'
                    }`}
                  >
                    {c}
                  </button>
                </li>
              );
            })}
          </ul>
        </nav>

        {/* 右侧题目列表 */}
        <div className="min-w-0 flex-1">
          {/* 题干搜索:在当前科目内模糊匹配 */}
          <div className="relative mb-4">
            <input
              value={keyword}
              onChange={(e) => setKeyword(e.target.value)}
              placeholder="搜索题干关键词…"
              className="w-full rounded-lg border border-ink/15 bg-white/60 px-3 py-2 pr-9 text-sm outline-none focus:border-sky focus:ring-2 focus:ring-sky/20"
            />
            {keyword && (
              <button
                onClick={() => setKeyword('')}
                className="absolute right-2 top-1/2 -translate-y-1/2 text-ink/40 hover:text-ink"
                aria-label="清空搜索"
              >
                ✕
              </button>
            )}
          </div>

          {err && <p className="mb-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-600">{err}</p>}
          {loading && <p className="mb-4 text-sm text-ink/40">加载中...</p>}
          {!loading && items.length === 0 && !err && (
            <p className="rounded-2xl bg-white/60 backdrop-blur-xl p-8 text-center text-ink/50 shadow-sm ring-1 ring-white/55">
              {searchKw ? `没有匹配「${searchKw}」的题目。` : '该科目暂无题目。管理员可在后台导入 Excel 题库。'}
            </p>
          )}
          <div className="space-y-4">
            {items.map((q, i) => (
              <QuestionCard key={q.id} q={q} index={(page - 1) * pageSize + i + 1} />
            ))}
          </div>

          {/* 分页栏 */}
          {total > 0 && (
            <div className="mt-6 flex flex-wrap items-center justify-end gap-3 text-sm text-ink/60">
              <select
                value={pageSize}
                onChange={(e) => setPageSize(Number(e.target.value))}
                className="rounded-lg border border-ink/15 px-2 py-1 outline-none focus:border-sky"
              >
                {PAGE_SIZES.map((s) => (
                  <option key={s} value={s}>
                    {s}条/页
                  </option>
                ))}
              </select>
              <span>共 {total} 条</span>
              <div className="flex items-center gap-1">
                <button
                  onClick={() => setPage((p) => Math.max(1, p - 1))}
                  disabled={page <= 1}
                  className="rounded-md border border-ink/15 px-2 py-1 hover:bg-mist disabled:opacity-40"
                >
                  ‹
                </button>
                <span className="px-2">
                  {page} / {totalPages}
                </span>
                <button
                  onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                  disabled={page >= totalPages}
                  className="rounded-md border border-ink/15 px-2 py-1 hover:bg-mist disabled:opacity-40"
                >
                  ›
                </button>
              </div>
              <span className="flex items-center gap-1">
                前往
                <input
                  type="number"
                  min={1}
                  max={totalPages}
                  value={jumpTo}
                  onChange={(e) => setJumpTo(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key !== 'Enter') return;
                    commitJump();
                  }}
                  className="w-14 rounded-md border border-ink/15 px-2 py-1 text-center outline-none focus:border-sky"
                />
                页
                <button
                  onClick={commitJump}
                  className="rounded-md border border-sky/35 px-2 py-1 font-medium text-sky hover:bg-sky/5"
                >
                  跳转
                </button>
              </span>
            </div>
          )}
        </div>
      </div>
    </main>
  );
}

function QuestionCard({ q, index }: { q: QuestionItem; index: number }) {
  const [picked, setPicked] = useState<string[]>([]);
  const [answer, setAnswer] = useState<{ answer: string; analysis: string } | null>(null);
  const [showComments, setShowComments] = useState(false);

  function toggle(key: string) {
    if (answer) return; // 已揭晓答案后锁定
    if (q.type === 'single') {
      setPicked([key]);
    } else {
      setPicked((p) => (p.includes(key) ? p.filter((k) => k !== key) : [...p, key]));
    }
  }

  async function reveal() {
    try {
      const result = await api.questionAnswer(q.id);
      setAnswer(result);
      const pickedKey = [...picked].sort().join('');
      await api.recordStudyWrong(q.id, pickedKey || result.answer);
    } catch {
      /* 静默:答案获取失败不致命,用户可重试 */
    }
  }

  const correctSet = new Set(answer?.answer.split('') ?? []);
  const pickedKey = [...picked].sort().join('');
  const isRight = answer && pickedKey === answer.answer;

  return (
    <section className="rounded-2xl bg-white/60 backdrop-blur-xl p-6 shadow-sm ring-1 ring-white/55">
      <div className="mb-3 flex items-start gap-2">
        <span className="rounded-md bg-mist px-2 py-0.5 text-xs font-medium text-ink/60">
          {index} · {q.type === 'single' ? '单选' : '多选'}
        </span>
        <div className="min-w-0 flex-1">
          <p className="font-medium text-ink">{q.stem}</p>
          <QuestionImages urls={q.imageUrls} />
        </div>
      </div>

      <div className="space-y-2">
        {q.options.map((o) => {
          const chosen = picked.includes(o.key);
          const correct = answer && correctSet.has(o.key);
          const cls = answer
            ? correct
              ? 'border-sky/50 bg-sky/5 text-ink'
              : chosen
                ? 'border-red-300 bg-red-50 text-red-600'
                : 'border-ink/10 text-ink/60'
            : chosen
              ? 'border-steel bg-steel/5 text-ink'
              : 'border-ink/10 text-ink/70 hover:border-steel/40';
          return (
            <button
              key={o.key}
              onClick={() => toggle(o.key)}
              className={`flex w-full items-center gap-3 rounded-lg border px-3 py-2 text-left transition ${cls}`}
            >
              <span className="font-mono text-sm">{o.key}</span>
              <span className="text-sm">{o.text}</span>
            </button>
          );
        })}
      </div>

      <div className="mt-4 flex items-center gap-3">
        {!answer ? (
          <button
            onClick={reveal}
            className="rounded-lg bg-sky px-5 py-2 text-sm font-medium text-white hover:bg-steel"
          >
            查看答案
          </button>
        ) : (
          <span className={`text-sm font-medium ${isRight ? 'text-sky' : 'text-red-500'}`}>
            {picked.length ? (isRight ? '回答正确' : '回答错误') : '正确答案'} · {answer.answer}
          </span>
        )}
        <button
          onClick={() => setShowComments((s) => !s)}
          className="text-sm text-ink/50 hover:text-ink"
        >
          {showComments ? '收起评论' : '评论'}
        </button>
      </div>

      {answer?.analysis && (
        <p className="mt-3 rounded-lg bg-mist px-4 py-3 text-sm text-ink/70">解析:{answer.analysis}</p>
      )}

      {showComments && <Comments questionId={q.id} />}
    </section>
  );
}

function QuestionImages({ urls }: { urls?: string[] }) {
  if (!urls?.length) return null;
  return (
    <div className="mt-3 space-y-2">
      {urls.map((url) => (
        <img
          key={url}
          src={assetUrl(url)}
          alt="题目配图"
          className="max-h-[520px] max-w-full rounded-lg border border-ink/10 object-contain"
        />
      ))}
    </div>
  );
}

// apps/student-uni/src/pages/study/index.vue
<script setup lang="ts">
import { onShow } from '@dcloudio/uni-app';
import { ref } from 'vue';
import { api, assetUrl, requireLogin, type CommentItem, type QuestionItem } from '@/utils/api';

const categories = ref<string[]>([]);
const category = ref('');
const keyword = ref('');
const questions = ref<QuestionItem[]>([]);
const picked = ref<Record<string, string[]>>({});
const answers = ref<Record<string, { answer: string; analysis: string }>>({});
const page = ref(1);
const jumpValue = ref('1');
const pageSizeOptions = [10, 20, 30];
const pageSize = ref(10);
const total = ref(0);
const loading = ref(false);
const commentOpen = ref<Record<string, boolean>>({});
const commentInputs = ref<Record<string, string>>({});
const commentLists = ref<Record<string, CommentItem[]>>({});

function toast(message: string) {
  uni.showToast({ title: message, icon: 'none' });
}

async function loadCategories() {
  const rows = await api.categories();
  categories.value = rows;
  if (!category.value && rows.length) {
    category.value = rows[0];
  }
}

async function loadQuestions(reset = false) {
  if (!requireLogin()) return;
  if (reset) {
    page.value = 1;
    jumpValue.value = '1';
  }
  if (!category.value) return;
  loading.value = true;
  try {
    const res = await api.questions({
      usage: 'study',
      category: category.value,
      keyword: keyword.value.trim() || undefined,
      page: page.value,
      pageSize: pageSize.value,
    });
    questions.value = res.items;
    total.value = res.total;
  } catch (e) {
    toast((e as Error).message);
  } finally {
    loading.value = false;
  }
}

async function reveal(id: string) {
  if (answers.value[id]) return;
  try {
    const result = await api.questionAnswer(id);
    answers.value[id] = result;
    const pickedKey = [...(picked.value[id] || [])].sort().join('');
    if (pickedKey && pickedKey !== result.answer) {
      await api.recordStudyWrong(id, pickedKey);
    }
  } catch (e) {
    toast((e as Error).message);
  }
}

function toggle(q: QuestionItem, key: string) {
  if (answers.value[q.id]) return;
  const cur = picked.value[q.id] || [];
  if (q.type === 'single') {
    picked.value[q.id] = [key];
    return;
  }
  picked.value[q.id] = cur.includes(key) ? cur.filter((item) => item !== key) : [...cur, key].sort();
}

function isCorrect(id: string, key: string) {
  return Boolean(answers.value[id]?.answer.includes(key));
}

function openExam() {
  uni.switchTab({ url: '/pages/exam/index' });
}

function changeCategory(e: { detail: { value: number } }) {
  category.value = categories.value[Number(e.detail.value)] || '';
  picked.value = {};
  answers.value = {};
  loadQuestions(true);
}

function changePageSize(e: { detail: { value: number } }) {
  pageSize.value = pageSizeOptions[Number(e.detail.value)] || pageSize.value;
  picked.value = {};
  answers.value = {};
  loadQuestions(true);
}

function nextPage(delta: number) {
  const maxPage = Math.max(1, Math.ceil(total.value / pageSize.value));
  const next = Math.min(maxPage, Math.max(1, page.value + delta));
  if (next === page.value) return;
  page.value = next;
  jumpValue.value = String(next);
  picked.value = {};
  answers.value = {};
  loadQuestions();
}

function jumpPage() {
  const maxPage = Math.max(1, Math.ceil(total.value / pageSize.value));
  const next = Math.min(maxPage, Math.max(1, Number(jumpValue.value) || 1));
  jumpValue.value = String(next);
  if (next === page.value) return;
  page.value = next;
  picked.value = {};
  answers.value = {};
  loadQuestions();
}

async function toggleComments(questionId: string) {
  commentOpen.value[questionId] = !commentOpen.value[questionId];
  if (!commentOpen.value[questionId] || commentLists.value[questionId]) return;
  try {
    commentLists.value[questionId] = await api.comments(questionId);
  } catch (e) {
    toast((e as Error).message);
  }
}

async function addComment(questionId: string) {
  const content = (commentInputs.value[questionId] || '').trim();
  if (!content) return;
  try {
    const created = await api.addComment(questionId, content);
    commentLists.value[questionId] = [created, ...(commentLists.value[questionId] || [])];
    commentInputs.value[questionId] = '';
  } catch (e) {
    toast((e as Error).message);
  }
}

onShow(async () => {
  if (!requireLogin()) return;
  try {
    await loadCategories();
    await loadQuestions();
  } catch (e) {
    toast((e as Error).message);
  }
});
</script>

<template>
  <view class="page study-page">
    <view class="header">
      <text class="title">专题学习</text>
      <text class="subtitle">顺序学习与模拟考试。</text>
    </view>

    <view class="subprojects">
      <view class="subproject active">
        <text class="subproject-title">顺序学习</text>
        <text class="subproject-desc">按科目顺序刷题,答错后进入错题本。</text>
      </view>
      <view class="subproject" @tap="openExam">
        <text class="subproject-title">模拟考试</text>
        <text class="subproject-desc">进入模拟考试,开始考试部分保持不变。</text>
      </view>
    </view>

    <view class="card filters">
      <picker mode="selector" :range="categories" @change="changeCategory">
        <view class="select">{{ category || '选择科目' }}</view>
      </picker>
      <input v-model="keyword" class="input" placeholder="搜索题干关键词" confirm-type="search" @confirm="loadQuestions(true)" />
      <button class="btn" @tap="loadQuestions(true)">搜索</button>
    </view>

    <view class="list-meta">
      <text>当前科目共 {{ total }} 题</text>
      <picker mode="selector" :range="pageSizeOptions.map((s) => `${s}题/页`)" @change="changePageSize">
        <view class="page-size">{{ pageSize }}题/页</view>
      </picker>
    </view>

    <view v-if="loading" class="empty">加载中...</view>
    <view v-else-if="questions.length === 0" class="empty">当前科目暂无题目。</view>

    <view class="question-list">
        <view v-for="(q, index) in questions" :key="q.id" class="card question-card">
        <view class="question-head">
          <text class="badge">{{ (page - 1) * pageSize + index + 1 }} · {{ q.type === 'single' ? '单选' : '多选' }}</text>
          <text class="stem">{{ q.stem }}</text>
          <image
            v-for="url in q.imageUrls || []"
            :key="url"
            :src="assetUrl(url)"
            mode="widthFix"
            class="question-image"
          />
        </view>
        <view class="options">
          <view
            v-for="option in q.options"
            :key="option.key"
            :class="[
              'option',
              (picked[q.id] || []).includes(option.key) && 'chosen',
              answers[q.id] && isCorrect(q.id, option.key) && 'correct',
              answers[q.id] && (picked[q.id] || []).includes(option.key) && !isCorrect(q.id, option.key) && 'wrong',
            ]"
            @tap="toggle(q, option.key)"
          >
            <text class="option-key">{{ option.key }}</text>
            <text class="option-text">{{ option.text }}</text>
          </view>
        </view>
        <view class="question-actions">
          <button v-if="!answers[q.id]" class="btn secondary action" @tap="reveal(q.id)">查看答案</button>
          <button class="btn secondary action" @tap="toggleComments(q.id)">
            {{ commentOpen[q.id] ? '收起评论' : '评论' }}
          </button>
        </view>
        <view v-if="answers[q.id]" class="answer-box">
          <text class="answer">答案: {{ answers[q.id].answer }}</text>
          <text v-if="answers[q.id].analysis" class="analysis">解析: {{ answers[q.id].analysis }}</text>
        </view>
        <view v-if="commentOpen[q.id]" class="comment-box">
          <view class="comment-form">
            <input v-model="commentInputs[q.id]" class="comment-input" placeholder="写下你的想法..." />
            <button class="btn comment-submit" @tap="addComment(q.id)">发表</button>
          </view>
          <view v-if="(commentLists[q.id] || []).length === 0" class="comment-empty">暂无评论</view>
          <view v-for="c in commentLists[q.id] || []" :key="c.id" class="comment-item">
            <text class="comment-name">{{ c.nickname }}</text>
            <text class="comment-content">{{ c.content }}</text>
          </view>
        </view>
      </view>
    </view>

    <view class="pager">
      <button class="btn secondary pager-btn" @tap="nextPage(-1)">上一页</button>
      <text class="pager-text">第 {{ page }} / {{ Math.max(1, Math.ceil(total / pageSize)) }} 页</text>
      <button class="btn secondary pager-btn" @tap="nextPage(1)">下一页</button>
    </view>
    <view v-if="total > pageSize" class="jump-row">
      <text class="jump-label">跳转到</text>
      <input v-model="jumpValue" class="jump-input" type="number" confirm-type="done" @confirm="jumpPage" />
      <text class="jump-label">页</text>
      <button class="btn secondary jump-btn" @tap="jumpPage">跳转</button>
    </view>
  </view>
</template>

<style scoped lang="scss">
.study-page,
.question-list,
.filters,
.list-meta,
.question-card,
.options,
.subprojects,
.answer-box,
.comment-box {
  display: flex;
  flex-direction: column;
}

.study-page {
  gap: 26rpx;
}

.subprojects {
  gap: 18rpx;
}

.subproject {
  background: rgba(255, 255, 255, 0.7);
  border: 2rpx solid rgba(255, 255, 255, 0.7);
  border-radius: 24rpx;
  padding: 24rpx;
}

.subproject.active {
  background: rgba(31, 111, 235, 0.08);
  border-color: rgba(31, 111, 235, 0.28);
}

.subproject-title {
  color: #111827;
  font-size: 30rpx;
  font-weight: 700;
}

.subproject-desc {
  color: rgba(17, 24, 39, 0.55);
  font-size: 24rpx;
  margin-top: 8rpx;
}

.header,
.filters,
.question-card,
.answer-box {
  gap: 18rpx;
}

.select {
  background: #fff;
  border: 2rpx solid rgba(17, 24, 39, 0.1);
  border-radius: 18rpx;
  color: #111827;
  font-size: 28rpx;
  min-height: 88rpx;
  padding: 24rpx;
}

.list-meta {
  align-items: center;
  color: rgba(17, 24, 39, 0.55);
  display: flex;
  flex-direction: row;
  font-size: 24rpx;
  justify-content: space-between;
}

.page-size {
  background: rgba(255, 255, 255, 0.7);
  border: 2rpx solid rgba(17, 24, 39, 0.1);
  border-radius: 14rpx;
  color: #111827;
  padding: 12rpx 18rpx;
}

.empty {
  color: rgba(17, 24, 39, 0.45);
  font-size: 28rpx;
  padding: 48rpx 0;
  text-align: center;
}

.question-list {
  gap: 22rpx;
}

.question-head {
  display: flex;
  flex-direction: column;
  gap: 14rpx;
}

.badge {
  align-self: flex-start;
  background: rgba(31, 111, 235, 0.1);
  border-radius: 8rpx;
  color: #1f6feb;
  font-size: 22rpx;
  padding: 6rpx 10rpx;
}

.stem {
  color: #111827;
  font-size: 30rpx;
  font-weight: 700;
  line-height: 1.6;
}

.question-image {
  border-radius: 16rpx;
  margin-top: 8rpx;
  width: 100%;
}

.options {
  gap: 12rpx;
}

.option {
  background: rgba(255, 255, 255, 0.62);
  border: 2rpx solid transparent;
  border-radius: 16rpx;
  display: flex;
  gap: 16rpx;
  padding: 18rpx;
}

.option.chosen {
  border-color: #38577a;
}

.option.correct {
  background: rgba(31, 111, 235, 0.08);
  border-color: rgba(31, 111, 235, 0.35);
}

.option.wrong {
  background: #fee2e2;
  border-color: #fca5a5;
}

.option-key,
.answer {
  color: #1f6feb;
  font-weight: 700;
}

.option-text,
.analysis {
  color: rgba(17, 24, 39, 0.7);
  flex: 1;
  font-size: 26rpx;
  line-height: 1.55;
}

.action {
  align-self: flex-start;
}

.answer-box {
  background: rgba(31, 111, 235, 0.08);
  border-radius: 16rpx;
  padding: 20rpx;
}

.question-actions,
.comment-form {
  align-items: center;
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  gap: 14rpx;
}

.comment-box {
  border-top: 2rpx solid rgba(17, 24, 39, 0.06);
  gap: 12rpx;
  padding-top: 16rpx;
}

.comment-input {
  background: #fff;
  border: 2rpx solid rgba(17, 24, 39, 0.12);
  border-radius: 16rpx;
  flex: 1;
  min-height: 72rpx;
  min-width: 300rpx;
  padding: 0 20rpx;
}

.comment-submit,
.jump-btn {
  min-height: 68rpx;
}

.comment-empty,
.comment-item {
  color: rgba(17, 24, 39, 0.52);
  font-size: 24rpx;
}

.comment-item {
  background: rgba(255, 255, 255, 0.58);
  border-radius: 14rpx;
  padding: 14rpx 16rpx;
}

.comment-name {
  color: rgba(17, 24, 39, 0.6);
  font-weight: 700;
  margin-right: 12rpx;
}

.comment-content {
  color: rgba(17, 24, 39, 0.76);
}

.pager {
  align-items: center;
  display: flex;
  gap: 16rpx;
  justify-content: space-between;
}

.pager-btn {
  min-height: 72rpx;
  min-width: 150rpx;
}

.pager-text {
  color: rgba(17, 24, 39, 0.55);
  font-size: 24rpx;
}

.jump-row {
  align-items: center;
  display: flex;
  flex-direction: row;
  gap: 12rpx;
  justify-content: center;
}

.jump-label {
  color: rgba(17, 24, 39, 0.55);
  font-size: 24rpx;
}

.jump-input {
  background: #fff;
  border: 2rpx solid rgba(17, 24, 39, 0.12);
  border-radius: 14rpx;
  color: #111827;
  min-height: 68rpx;
  text-align: center;
  width: 120rpx;
}
</style>
