// frontend/app/wrong/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { api, assetUrl, getToken, type WrongBookItem } from '@/lib/api';
import Comments from '@/components/Comments';

export default function WrongBookPage() {
  const router = useRouter();
  const [items, setItems] = useState<WrongBookItem[]>([]);
  const [category, setCategory] = useState('');
  const [err, setErr] = useState('');
  const [loading, setLoading] = useState(true);
  const categories = Array.from(new Set(items.map((item) => item.category).filter(Boolean))).sort();
  const filteredItems = items.filter((item) => !category || item.category === category);

  useEffect(() => {
    if (!getToken()) {
      router.push('/login');
      return;
    }
    api
      .wrongBook()
      .then(setItems)
      .catch((e) => setErr((e as Error).message))
      .finally(() => setLoading(false));
  }, [router]);

  function remove(questionId: string, source: WrongBookItem['source']) {
    setItems((l) => l.filter((i) => !(i.questionId === questionId && i.source === source)));
  }

  if (loading) {
    return <main className="flex min-h-screen items-center justify-center text-ink/50">加载中...</main>;
  }

  return (
    <main className="mx-auto max-w-3xl px-6 py-10">
      <a href="/" className="text-sm font-bold text-ink hover:text-sky">
        ← 返回首页
      </a>
      <h1 className="mb-1 mt-1 text-3xl font-semibold tracking-tight text-ink">错题本</h1>
      <p className="mb-6 text-sm text-ink/55">
        顺序学习答错的题会进入错题本；模拟考试错题请在考试回顾里查看。
      </p>
      <div className="mb-6 flex flex-wrap items-center gap-3">
        <select
          className="rounded-lg border border-ink/15 bg-white px-3 py-2 text-sm outline-none focus:border-sky"
          value={category}
          onChange={(e) => setCategory(e.target.value)}
        >
          <option value="">全部模块</option>
          {categories.map((name) => (
            <option key={name} value={name}>
              {name}
            </option>
          ))}
        </select>
        <span className="text-sm text-ink/45">{filteredItems.length} 题</span>
      </div>
      {err && <p className="mb-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-600">{err}</p>}
      {filteredItems.length === 0 && !err && (
        <p className="rounded-2xl bg-white/60 backdrop-blur-xl p-8 text-center text-ink/50 shadow-sm ring-1 ring-white/55">
          暂无顺序学习错题。
        </p>
      )}
      <div className="space-y-4">
        {filteredItems.map((q, i) => (
          <WrongCard key={`${q.source}:${q.questionId}`} q={q} index={i + 1} onMaster={() => remove(q.questionId, q.source)} />
        ))}
      </div>
    </main>
  );
}

function WrongCard({
  q,
  index,
  onMaster,
}: {
  q: WrongBookItem;
  index: number;
  onMaster: () => void;
}) {
  const [revealed, setRevealed] = useState(false);
  const [showComments, setShowComments] = useState(false);

  async function master() {
    try {
      await api.masterWrong(q.questionId, q.source);
      onMaster();
    } catch {
      /* 失败可重试 */
    }
  }

  const correctSet = new Set(q.answer.split(''));

  return (
    <section className="rounded-2xl bg-white/60 backdrop-blur-xl p-6 shadow-sm ring-1 ring-white/55">
      <div className="mb-3 flex items-start justify-between gap-3">
        <div className="flex items-start gap-2">
          <span className="rounded-md bg-mist px-2 py-0.5 text-xs font-medium text-ink/60">
            {index} · {q.type === 'single' ? '单选' : '多选'}
          </span>
          <div className="min-w-0 flex-1">
            <p className="font-medium text-ink">{q.stem}</p>
          </div>
        </div>
        <span className="shrink-0 rounded-md bg-red-50 px-2 py-0.5 text-xs text-red-500">
          错 {q.wrongCount} 次
        </span>
      </div>

      {revealed && <div className="space-y-2">
        {q.options.map((o) => {
          const correct = correctSet.has(o.key);
          const cls = correct ? 'border-green-300 bg-green-50 text-green-700' : 'border-ink/10 text-ink/60';
          return (
            <div
              key={o.key}
              className={`flex w-full items-center gap-3 rounded-lg border px-3 py-2 text-left transition ${cls}`}
            >
              <span className="font-mono text-sm">{o.key}</span>
              <span className="text-sm">{o.text}</span>
              {correct && <span className="ml-auto text-xs text-green-600">正确答案</span>}
            </div>
          );
        })}
      </div>}

      <div className="mt-4 flex flex-wrap items-center gap-3">
        {!revealed ? (
          <button
            onClick={() => setRevealed(true)}
            className="rounded-lg bg-sky px-5 py-2 text-sm font-medium text-white hover:bg-steel"
          >
            查看答案
          </button>
        ) : (
          <>
            <span className="text-sm font-medium text-green-600">正确答案 · {q.answer}</span>
            <button
              onClick={master}
              className="rounded-lg border border-sky/40 px-4 py-1.5 text-sm font-medium text-sky hover:bg-sky/5"
            >
              已掌握
            </button>
          </>
        )}
        <button onClick={() => setShowComments((s) => !s)} className="text-sm text-ink/50 hover:text-ink">
          {showComments ? '收起评论' : '评论'}
        </button>
      </div>

      {revealed && (q.analysis || q.imageUrls?.length) && (
        <div className="mt-3 rounded-lg bg-mist px-4 py-2 text-sm text-ink/65">
          {q.analysis && <p>解析:{q.analysis}</p>}
          <QuestionImages urls={q.imageUrls} />
        </div>
      )}

      {showComments && <Comments questionId={q.questionId} />}
    </section>
  );
}

function QuestionImages({ urls }: { urls?: string[] }) {
  if (!urls?.length) return null;
  return (
    <div className="mt-3 space-y-2">
      {urls.map((url) => (
        <img
          key={url}
          src={assetUrl(url)}
          alt="解析配图"
          className="max-h-[520px] max-w-full rounded-lg border border-ink/10 object-contain"
        />
      ))}
    </div>
  );
}

// apps/student-uni/src/pages/wrong/index.vue
<script setup lang="ts">
import { onShow } from '@dcloudio/uni-app';
import { computed, ref } from 'vue';
import { api, assetUrl, requireLogin, type CommentItem, type WrongBookItem, type WrongQuestionSource } from '@/utils/api';

const items = ref<WrongBookItem[]>([]);
const revealed = ref<Record<string, boolean>>({});
const category = ref('');
const loading = ref(false);
const commentOpen = ref<Record<string, boolean>>({});
const commentInputs = ref<Record<string, string>>({});
const commentLists = ref<Record<string, CommentItem[]>>({});

function toast(message: string) {
  uni.showToast({ title: message, icon: 'none' });
}

const categories = computed(() => Array.from(new Set(items.value.map((item) => item.category).filter(Boolean))).sort());
const filteredItems = computed(() => items.value.filter((item) => !category.value || item.category === category.value));

function itemKey(q: WrongBookItem) {
  return `${q.source}:${q.questionId}`;
}

function changeCategory(e: { detail: { value: number } }) {
  const idx = Number(e.detail.value);
  category.value = idx === 0 ? '' : categories.value[idx - 1] || '';
}

async function load() {
  if (!requireLogin()) return;
  loading.value = true;
  try {
    items.value = await api.wrongBook();
  } catch (e) {
    toast((e as Error).message);
  } finally {
    loading.value = false;
  }
}

function isCorrect(q: WrongBookItem, key: string) {
  return q.answer.includes(key);
}

async function master(questionId: string, source: WrongQuestionSource) {
  try {
    await api.masterWrong(questionId, source);
    items.value = items.value.filter((item) => !(item.questionId === questionId && item.source === source));
  } catch (e) {
    toast((e as Error).message);
  }
}

async function toggleComments(questionId: string) {
  commentOpen.value[questionId] = !commentOpen.value[questionId];
  if (!commentOpen.value[questionId] || commentLists.value[questionId]) return;
  try {
    commentLists.value[questionId] = await api.comments(questionId);
  } catch (e) {
    toast((e as Error).message);
  }
}

async function addComment(questionId: string) {
  const content = (commentInputs.value[questionId] || '').trim();
  if (!content) return;
  try {
    const created = await api.addComment(questionId, content);
    commentLists.value[questionId] = [created, ...(commentLists.value[questionId] || [])];
    commentInputs.value[questionId] = '';
  } catch (e) {
    toast((e as Error).message);
  }
}

async function removeComment(questionId: string, commentId: string) {
  uni.showModal({
    title: '删除评论',
    content: '确认删除这条评论吗？',
    success: async (res) => {
      if (!res.confirm) return;
      try {
        await api.deleteComment(commentId);
        commentLists.value[questionId] = (commentLists.value[questionId] || []).filter((item) => item.id !== commentId);
      } catch (e) {
        toast((e as Error).message);
      }
    },
  });
}

onShow(load);
</script>

<template>
  <view class="page wrong-page">
    <view class="header">
      <text class="title">错题本</text>
      <text class="subtitle">顺序学习答错的题会进入错题本，模拟考试错题请在考试回顾里查看。</text>
    </view>

    <view class="filter">
      <picker mode="selector" :range="['全部模块', ...categories]" @change="changeCategory">
        <view class="select">{{ category || '全部模块' }}</view>
      </picker>
      <text class="count">{{ filteredItems.length }} 题</text>
    </view>

    <view v-if="loading" class="empty">加载中...</view>
    <view v-else-if="filteredItems.length === 0" class="empty">
      暂无顺序学习错题。
    </view>

    <view class="wrong-list">
      <view v-for="(q, index) in filteredItems" :key="`${q.source}:${q.questionId}`" class="card wrong-card">
        <view class="question-head">
          <text class="badge">{{ index + 1 }} · {{ q.type === 'single' ? '单选' : '多选' }}</text>
          <text class="wrong-count">错 {{ q.wrongCount }} 次</text>
        </view>
        <text class="stem">{{ q.stem }}</text>
        <view v-if="revealed[itemKey(q)]" class="options">
          <view
            v-for="option in q.options"
            :key="option.key"
            :class="[
              'option',
              revealed[itemKey(q)] && isCorrect(q, option.key) && 'correct',
            ]"
          >
            <text class="option-key">{{ option.key }}</text>
            <text class="option-text">{{ option.text }}</text>
          </view>
        </view>
        <view class="actions">
          <button v-if="!revealed[itemKey(q)]" class="btn" @tap="revealed[itemKey(q)] = true">查看答案</button>
          <template v-else>
            <text class="answer">正确答案: {{ q.answer }}</text>
            <button class="btn secondary master" @tap="master(q.questionId, q.source)">已掌握</button>
          </template>
          <button class="btn secondary master" @tap="toggleComments(q.questionId)">
            {{ commentOpen[q.questionId] ? '收起评论' : '评论' }}
          </button>
        </view>
        <text v-if="revealed[itemKey(q)] && q.analysis" class="analysis">解析: {{ q.analysis }}</text>
        <image
          v-for="url in revealed[itemKey(q)] ? q.imageUrls || [] : []"
          :key="url"
          :src="assetUrl(url)"
          mode="widthFix"
          class="question-image"
        />
        <view v-if="commentOpen[q.questionId]" class="comment-box">
          <view class="comment-form">
            <input v-model="commentInputs[q.questionId]" class="comment-input" placeholder="写下你的想法..." />
            <button class="btn comment-submit" @tap="addComment(q.questionId)">发表</button>
          </view>
          <view v-if="(commentLists[q.questionId] || []).length === 0" class="comment-empty">暂无评论</view>
          <view v-for="c in commentLists[q.questionId] || []" :key="c.id" class="comment-item">
            <view class="comment-head">
              <text class="comment-name">{{ c.nickname }}</text>
              <text v-if="c.canDelete" class="comment-delete" @tap="removeComment(q.questionId, c.id)">删除</text>
            </view>
            <text class="comment-content">{{ c.content }}</text>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<style scoped lang="scss">
.wrong-page,
.wrong-list,
.wrong-card,
.options,
.filter,
.comment-box {
  display: flex;
  flex-direction: column;
}

.wrong-page,
.wrong-list {
  gap: 22rpx;
}

.header,
.wrong-card,
.options {
  gap: 16rpx;
}

.empty {
  color: rgba(17, 24, 39, 0.45);
  font-size: 28rpx;
  padding: 48rpx 0;
  text-align: center;
}

.filter {
  align-items: center;
  flex-direction: row;
  gap: 16rpx;
}

.select {
  background: #fff;
  border: 2rpx solid rgba(17, 24, 39, 0.1);
  border-radius: 16rpx;
  color: #111827;
  font-size: 26rpx;
  min-width: 260rpx;
  padding: 18rpx 22rpx;
}

.count {
  color: rgba(17, 24, 39, 0.45);
  font-size: 24rpx;
}

.question-head {
  align-items: center;
  display: flex;
  justify-content: space-between;
}

.badge {
  background: rgba(31, 111, 235, 0.1);
  border-radius: 8rpx;
  color: #1f6feb;
  font-size: 22rpx;
  padding: 6rpx 10rpx;
}

.wrong-count {
  color: #dc2626;
  font-size: 24rpx;
}

.stem {
  color: #111827;
  font-size: 30rpx;
  font-weight: 700;
  line-height: 1.6;
}

.question-image {
  border-radius: 12rpx;
  margin-top: 8rpx;
  max-width: 100%;
  width: 100%;
}

.option {
  background: rgba(255, 255, 255, 0.62);
  border: 2rpx solid transparent;
  border-radius: 16rpx;
  display: flex;
  gap: 16rpx;
  padding: 18rpx;
}

.option.chosen {
  border-color: #38577a;
}

.option.correct {
  background: rgba(31, 111, 235, 0.08);
  border-color: rgba(31, 111, 235, 0.35);
}

.option.wrong {
  background: #fee2e2;
  border-color: #fca5a5;
}

.option-key,
.answer {
  color: #1f6feb;
  font-weight: 700;
}

.option-text,
.analysis {
  color: rgba(17, 24, 39, 0.7);
  flex: 1;
  font-size: 26rpx;
  line-height: 1.55;
}

.actions {
  align-items: center;
  display: flex;
  flex-wrap: wrap;
  gap: 16rpx;
}

.master {
  min-height: 72rpx;
}

.comment-box {
  border-top: 2rpx solid rgba(17, 24, 39, 0.06);
  gap: 12rpx;
  padding-top: 16rpx;
}

.comment-form {
  align-items: center;
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  gap: 14rpx;
}

.comment-input {
  background: #fff;
  border: 2rpx solid rgba(17, 24, 39, 0.12);
  border-radius: 16rpx;
  flex: 1;
  min-height: 72rpx;
  min-width: 300rpx;
  padding: 0 20rpx;
}

.comment-submit {
  min-height: 68rpx;
}

.comment-empty,
.comment-item {
  color: rgba(17, 24, 39, 0.52);
  font-size: 24rpx;
}

.comment-item {
  background: rgba(255, 255, 255, 0.58);
  border-radius: 14rpx;
  display: flex;
  flex-direction: column;
  gap: 8rpx;
  padding: 14rpx 16rpx;
}

.comment-head {
  align-items: center;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}

.comment-name {
  color: rgba(17, 24, 39, 0.6);
  font-weight: 700;
}

.comment-delete {
  color: #dc2626;
  font-weight: 700;
}

.comment-content {
  color: rgba(17, 24, 39, 0.76);
}
</style>
