// frontend/app/exam/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { api, assetUrl, getToken, type ExamResult, type GradedItem, type PaperQuestion } from '@/lib/api';
import Comments from '@/components/Comments';

type Phase = 'idle' | 'taking' | 'result';

const EXAM_CATEGORY_COUNTS: Record<string, number> = {
  'M1 航空概论': 32,
  'M2 航空器维修': 50,
  'M3 飞机结构和系统': 182,
  'M5 航空涡轮发动机': 70,
  'M9 航空英语': 60,
};

export default function ExamPage() {
  const router = useRouter();
  const [phase, setPhase] = useState<Phase>('idle');
  const [categories, setCategories] = useState<string[]>([]);
  const [category, setCategory] = useState('');
  const [attemptId, setAttemptId] = useState('');
  const [questions, setQuestions] = useState<PaperQuestion[]>([]);
  const [answers, setAnswers] = useState<Record<string, string[]>>({});
  const [result, setResult] = useState<ExamResult | null>(null);
  const [err, setErr] = useState('');
  const [busy, setBusy] = useState(false);
  const [unansweredCursor, setUnansweredCursor] = useState(-1);

  useEffect(() => {
    if (!getToken()) {
      router.push('/login');
      return;
    }
    api
      .categories()
      .then((list) => {
        const examCategories = list.filter((name) => EXAM_CATEGORY_COUNTS[name]);
        setCategories(examCategories);
        setCategory((current) => current || examCategories[0] || '');
      })
      .catch(() => undefined);
  }, [router]);

  async function start() {
    setErr('');
    if (!category) {
      setErr('请选择考试科目');
      return;
    }
    setBusy(true);
    try {
      const r = await api.startExam(undefined, category);
      setAttemptId(r.attemptId);
      setQuestions(r.questions);
      setAnswers({});
      setUnansweredCursor(-1);
      setResult(null);
      setPhase('taking');
    } catch (e) {
      setErr((e as Error).message);
    } finally {
      setBusy(false);
    }
  }

  function pick(q: PaperQuestion, key: string) {
    setAnswers((prev) => {
      const cur = prev[q.id] ?? [];
      if (q.type === 'single') return { ...prev, [q.id]: [key] };
      return { ...prev, [q.id]: cur.includes(key) ? cur.filter((k) => k !== key) : [...cur, key] };
    });
  }

  async function submit() {
    setErr('');
    setBusy(true);
    try {
      const payload: Record<string, string> = {};
      questions.forEach((q) => (payload[q.id] = [...(answers[q.id] ?? [])].sort().join('')));
      const r = await api.submitExam(attemptId, payload);
      setResult(r);
      setPhase('result');
    } catch (e) {
      setErr((e as Error).message);
    } finally {
      setBusy(false);
    }
  }

  const answeredCount = questions.filter((q) => (answers[q.id] ?? []).length > 0).length;
  const unfinishedCount = Math.max(0, questions.length - answeredCount);

  function jumpToNextUnanswered() {
    for (let step = 1; step <= questions.length; step++) {
      const idx = (unansweredCursor + step) % questions.length;
      const q = questions[idx];
      if ((answers[q.id] ?? []).length === 0) {
        setUnansweredCursor(idx);
        document.getElementById(`exam-q-${q.id}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
        return;
      }
    }
  }

  return (
    <main className="mx-auto max-w-3xl px-6 py-10">
      <a href="/" className="text-sm font-bold text-ink hover:text-sky">
        ← 返回首页
      </a>
      <h1 className="mb-6 mt-1 text-3xl font-semibold tracking-tight text-ink">在线考试</h1>
      {err && <p className="mb-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-600">{err}</p>}

      {phase === 'idle' && (
        <div className="rounded-2xl bg-white/60 backdrop-blur-xl p-7 shadow-sm ring-1 ring-white/55">
          <p className="mb-4 text-ink/70">从题库随机组卷,提交后自动判分。</p>
          <div className="flex flex-wrap items-end gap-3">
            <div>
              <label className="mb-1 block text-xs text-ink/60">科目</label>
              <select
                className="rounded-lg border border-ink/15 px-3 py-2 outline-none focus:border-sky"
                value={category}
                onChange={(e) => setCategory(e.target.value)}
              >
                {categories.map((c) => (
                  <option key={c} value={c}>
                    {c}
                  </option>
                ))}
              </select>
              {category && (
                <p className="mt-1 text-xs text-ink/45">本次考试 {EXAM_CATEGORY_COUNTS[category]} 题，考完为止</p>
              )}
            </div>
            <button
              onClick={start}
              disabled={busy}
              className="rounded-lg bg-steel px-6 py-2 font-medium text-white hover:bg-ink disabled:opacity-50"
            >
              开始考试
            </button>
          </div>
        </div>
      )}

      {phase === 'taking' && (
        <div className="space-y-4">
          <p className="text-sm text-ink/55">
            共 {questions.length} 题 · 已答 {answeredCount}
          </p>
          <div className="flex flex-wrap gap-2 text-sm font-medium">
            <span className="rounded-full bg-green-50 px-3 py-1 text-green-700">已完成 {answeredCount}</span>
            <button onClick={jumpToNextUnanswered} className="rounded-full bg-red-50 px-3 py-1 text-red-600">
              未答题 {unfinishedCount}
            </button>
          </div>
          {questions.map((q, i) => (
            <section id={`exam-q-${q.id}`} key={q.id} className="rounded-2xl bg-white/60 backdrop-blur-xl p-6 shadow-sm ring-1 ring-white/55">
              <div className="mb-3 flex items-start gap-2">
                <span className="rounded-md bg-mist px-2 py-0.5 text-xs font-medium text-ink/60">
                  {i + 1} · {q.type === 'single' ? '单选' : '多选'}
                </span>
                <div className="min-w-0 flex-1">
                  <p className="font-medium text-ink">{q.stem}</p>
                  <QuestionImages urls={q.stemImageUrls} alt="题干配图" />
                </div>
              </div>
              <div className="space-y-2">
                {q.options.map((o) => {
                  const chosen = (answers[q.id] ?? []).includes(o.key);
                  return (
                    <button
                      key={o.key}
                      onClick={() => pick(q, o.key)}
                      className={`flex w-full items-center gap-3 rounded-lg border px-3 py-2 text-left transition ${
                        chosen ? 'border-steel bg-steel/5 text-ink' : 'border-ink/10 text-ink/70 hover:border-steel/40'
                      }`}
                    >
                      <span className="font-mono text-sm">{o.key}</span>
                      <span className="text-sm">{o.text}</span>
                    </button>
                  );
                })}
              </div>
            </section>
          ))}
          <button
            onClick={submit}
            disabled={busy}
            className="w-full rounded-lg bg-sky py-3 font-medium text-white hover:bg-steel disabled:opacity-50"
          >
            交卷
          </button>
        </div>
      )}

      {phase === 'result' && result && (
        <div className="space-y-4">
          <div className="rounded-2xl bg-gradient-to-br from-steel to-ink p-7 text-center text-white">
            <p className="text-sm text-white/70">本次成绩</p>
            <p className="mt-1 text-5xl font-semibold">{result.score}</p>
            <p className="mt-2 text-sm text-white/70">
              答对 {result.correct} / {result.total} 题
            </p>
          </div>
          {result.details.map((d, i) => (
            <ResultCard key={d.questionId} d={d} index={i + 1} />
          ))}
          <button
            onClick={() => setPhase('idle')}
            className="w-full rounded-lg bg-steel py-3 font-medium text-white hover:bg-ink"
          >
            再考一次
          </button>
        </div>
      )}
    </main>
  );
}

// 复盘单题:对错标记 + 答案解析 + 可展开评论。
function ResultCard({ d, index }: { d: GradedItem; index: number }) {
  const [showComments, setShowComments] = useState(false);
  return (
    <section className="rounded-2xl bg-white/60 backdrop-blur-xl p-6 shadow-sm ring-1 ring-white/55">
      <div className="mb-3 flex items-start gap-2">
        <span
          className={`rounded-md px-2 py-0.5 text-xs font-medium ${
            d.isCorrect ? 'bg-sky/10 text-sky' : 'bg-red-50 text-red-500'
          }`}
        >
          {index} · {d.isCorrect ? '正确' : '错误'}
        </span>
        <div className="min-w-0 flex-1">
          <p className="font-medium text-ink">{d.stem}</p>
          <QuestionImages urls={d.stemImageUrls} alt="题干配图" />
        </div>
      </div>
      <p className="text-sm text-ink/70">
        你的答案:<span className="font-mono">{d.yourAnswer || '(未答)'}</span> · 正确答案:
        <span className="font-mono text-green-600">{d.correctAnswer}</span>
      </p>
      {(d.analysis || d.imageUrls?.length) && (
        <div className="mt-2 rounded-lg bg-mist px-4 py-2 text-sm text-ink/65">
          {d.analysis && <p>解析:{d.analysis}</p>}
          <QuestionImages urls={d.imageUrls} alt="解析配图" />
        </div>
      )}
      <button
        onClick={() => setShowComments((s) => !s)}
        className="mt-3 text-sm text-ink/50 hover:text-ink"
      >
        {showComments ? '收起评论' : '评论'}
      </button>
      {showComments && <Comments questionId={d.questionId} />}
    </section>
  );
}

function QuestionImages({ urls, alt }: { urls?: string[]; alt: string }) {
  if (!urls?.length) return null;
  return (
    <div className="mt-3 space-y-2">
      {urls.map((url) => (
        <img
          key={url}
          src={assetUrl(url)}
          alt={alt}
          className="max-h-[520px] max-w-full rounded-lg border border-ink/10 object-contain"
        />
      ))}
    </div>
  );
}

// apps/student-uni/src/pages/exam/index.vue
<script setup lang="ts">
import { onShow } from '@dcloudio/uni-app';
import { computed, ref } from 'vue';
import { api, assetUrl, requireLogin, type ExamResult, type PaperQuestion } from '@/utils/api';

const EXAM_CATEGORY_COUNTS: Record<string, number> = {
  'M1 航空概论': 32,
  'M2 航空器维修': 50,
  'M3 飞机结构和系统': 182,
  'M5 航空涡轮发动机': 70,
  'M9 航空英语': 60,
};

const categories = ref<string[]>([]);
const category = ref('');
const phase = ref<'idle' | 'taking' | 'result'>('idle');
const attemptId = ref('');
const questions = ref<PaperQuestion[]>([]);
const answers = ref<Record<string, string[]>>({});
const result = ref<ExamResult | null>(null);
const busy = ref(false);
const currentIndex = ref(0);
const touchStartX = ref(0);
const unansweredJumpIndex = ref(-1);

const answeredCount = computed(() => Object.values(answers.value).filter((v) => v.length > 0).length);
const unfinishedCount = computed(() => Math.max(0, questions.value.length - answeredCount.value));
const currentQuestion = computed(() => questions.value[currentIndex.value] || null);
const canPrev = computed(() => currentIndex.value > 0);
const canNext = computed(() => currentIndex.value < questions.value.length - 1);

function toast(message: string) {
  uni.showToast({ title: message, icon: 'none' });
}

async function loadCategories() {
  try {
    categories.value = (await api.categories()).filter((name) => EXAM_CATEGORY_COUNTS[name]);
    if (!category.value && categories.value.length > 0) {
      category.value = categories.value[0];
    }
  } catch {
    categories.value = [];
  }
}

async function start() {
  if (!requireLogin()) return;
  if (!category.value) {
    toast('请选择考试科目');
    return;
  }
  busy.value = true;
  try {
    const paper = await api.startExam(category.value);
    attemptId.value = paper.attemptId;
    questions.value = paper.questions;
    answers.value = {};
    result.value = null;
    currentIndex.value = 0;
    unansweredJumpIndex.value = -1;
    phase.value = 'taking';
  } catch (e) {
    toast((e as Error).message);
  } finally {
    busy.value = false;
  }
}

function pick(q: PaperQuestion, key: string) {
  const cur = answers.value[q.id] || [];
  if (q.type === 'single') {
    answers.value[q.id] = [key];
    if (currentQuestion.value?.id === q.id && canNext.value) {
      setTimeout(() => {
        if (currentQuestion.value?.id === q.id) moveQuestion(1);
      }, 180);
    }
    return;
  }
  answers.value[q.id] = cur.includes(key) ? cur.filter((k) => k !== key) : [...cur, key].sort();
}

function moveQuestion(delta: number) {
  if (questions.value.length === 0) return;
  const next = Math.min(questions.value.length - 1, Math.max(0, currentIndex.value + delta));
  if (next === currentIndex.value) return;
  currentIndex.value = next;
}

function jumpToNextUnanswered() {
  if (questions.value.length === 0) return;
  for (let step = 1; step <= questions.value.length; step++) {
    const idx = (unansweredJumpIndex.value + step) % questions.value.length;
    const q = questions.value[idx];
    if ((answers.value[q.id] || []).length === 0) {
      unansweredJumpIndex.value = idx;
      currentIndex.value = idx;
      return;
    }
  }
  toast('已全部完成');
}

function onTouchStart(e: { changedTouches?: Array<{ clientX: number }>; touches?: Array<{ clientX: number }> }) {
  touchStartX.value = e.changedTouches?.[0]?.clientX ?? e.touches?.[0]?.clientX ?? 0;
}

function onTouchEnd(e: { changedTouches?: Array<{ clientX: number }> }) {
  const endX = e.changedTouches?.[0]?.clientX ?? 0;
  const delta = endX - touchStartX.value;
  if (Math.abs(delta) < 60) return;
  moveQuestion(delta > 0 ? -1 : 1);
}

async function submit() {
  busy.value = true;
  try {
    const payload: Record<string, string> = {};
    questions.value.forEach((q) => {
      payload[q.id] = (answers.value[q.id] || []).join('');
    });
    result.value = await api.submitExam(attemptId.value, payload);
    phase.value = 'result';
  } catch (e) {
    toast((e as Error).message);
  } finally {
    busy.value = false;
  }
}

function changeCategory(e: { detail: { value: number } }) {
  const idx = Number(e.detail.value);
  category.value = categories.value[idx] || '';
}

onShow(() => {
  if (!requireLogin()) return;
  loadCategories();
});
</script>

<template>
  <view class="page exam-page">
    <view class="header">
      <text class="title">在线考试</text>
      <text class="subtitle">选择单科考试,交卷后自动判分并进入考试回顾。</text>
    </view>

    <view v-if="phase === 'idle'" class="card start-card">
      <picker mode="selector" :range="categories" @change="changeCategory">
        <view class="select">{{ category || '请选择考试科目' }}</view>
      </picker>
      <text v-if="category" class="hint">本次考试 {{ EXAM_CATEGORY_COUNTS[category] }} 题，考完为止</text>
      <button class="btn" :loading="busy" @tap="start">开始考试</button>
    </view>

    <view v-if="phase === 'taking'" class="taking" @touchstart="onTouchStart" @touchend="onTouchEnd">
      <text class="progress">共 {{ questions.length }} 题 · 已答 {{ answeredCount }}</text>
      <view class="exam-status">
        <text class="status-done">已完成 {{ answeredCount }} 题</text>
        <button class="status-pending" :disabled="unfinishedCount === 0" @tap.stop="jumpToNextUnanswered">
          <text>未答题 {{ unfinishedCount }}</text>
          <text class="pending-action">去作答</text>
          <text class="pending-arrow">&gt;</text>
        </button>
      </view>
      <view v-if="currentQuestion" class="card question-card">
        <view class="question-head">
          <text class="badge">{{ currentIndex + 1 }} / {{ questions.length }} · {{ currentQuestion.type === 'single' ? '单选' : '多选' }}</text>
          <text class="stem">{{ currentQuestion.stem }}</text>
        </view>
        <image
          v-for="url in currentQuestion.stemImageUrls || []"
          :key="url"
          :src="assetUrl(url)"
          mode="widthFix"
          class="question-image"
        />
        <view class="options">
          <view
            v-for="option in currentQuestion.options"
            :key="option.key"
            :class="['option', (answers[currentQuestion.id] || []).includes(option.key) && 'chosen']"
            @tap="pick(currentQuestion, option.key)"
          >
            <text class="option-key">{{ option.key }}</text>
            <text class="option-text">{{ option.text }}</text>
          </view>
        </view>
      </view>
      <view class="question-nav">
        <button class="btn secondary nav-btn" :disabled="!canPrev" @tap="moveQuestion(-1)">上一题</button>
        <text class="nav-text">{{ currentIndex + 1 }} / {{ questions.length }}</text>
        <button class="btn secondary nav-btn" :disabled="!canNext" @tap="moveQuestion(1)">下一题</button>
      </view>
      <button class="btn submit" :loading="busy" @tap="submit">交卷</button>
    </view>

    <view v-if="phase === 'result' && result" class="result-list">
      <view class="score-card">
        <text class="score-label">本次成绩</text>
        <text class="score">{{ result.score }}</text>
        <text class="score-label">答对 {{ result.correct }} / {{ result.total }} 题</text>
      </view>
      <view v-for="(d, index) in result.details" :key="d.questionId" class="card review-card">
        <text :class="['badge', d.isCorrect ? 'ok' : 'bad']">{{ index + 1 }} · {{ d.isCorrect ? '正确' : '错误' }}</text>
        <text class="stem">{{ d.stem }}</text>
        <image v-for="url in d.stemImageUrls || []" :key="url" :src="assetUrl(url)" mode="widthFix" class="question-image" />
        <text class="summary">你的答案: {{ d.yourAnswer || '(未答)' }} · 正确答案: {{ d.correctAnswer }}</text>
        <text v-if="d.analysis" class="analysis">解析: {{ d.analysis }}</text>
        <image v-for="url in d.imageUrls || []" :key="url" :src="assetUrl(url)" mode="widthFix" class="question-image" />
      </view>
      <button class="btn" @tap="phase = 'idle'">再考一次</button>
    </view>
  </view>
</template>

<style scoped lang="scss">
.exam-page,
.start-card,
.taking,
.question-card,
.question-head,
.options,
.question-nav,
.result-list,
.review-card {
  display: flex;
  flex-direction: column;
}

.exam-page,
.taking,
.result-list {
  gap: 24rpx;
}

.header,
.start-card,
.question-card,
.review-card {
  gap: 18rpx;
}

.select {
  background: #fff;
  border: 2rpx solid rgba(17, 24, 39, 0.1);
  border-radius: 18rpx;
  color: #111827;
  font-size: 28rpx;
  min-height: 88rpx;
  padding: 24rpx;
}

.progress,
.hint,
.summary,
.analysis {
  color: rgba(17, 24, 39, 0.6);
  font-size: 26rpx;
  line-height: 1.6;
}

.exam-status {
  align-items: center;
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  gap: 16rpx;
}

.status-done {
  color: rgba(17, 24, 39, 0.58);
  font-size: 26rpx;
  font-weight: 600;
}

.status-pending {
  align-items: center;
  background: #fff7ed;
  border: 2rpx solid #fdba74;
  border-radius: 999rpx;
  box-shadow: 0 8rpx 20rpx rgba(234, 88, 12, 0.12);
  color: #c2410c;
  display: flex;
  flex-direction: row;
  gap: 12rpx;
  font-size: 26rpx;
  font-weight: 700;
  line-height: 1;
  margin: 0;
  min-height: 64rpx;
  padding: 0 12rpx 0 22rpx;
}

.status-pending[disabled] {
  background: rgba(17, 24, 39, 0.05);
  border: 0;
  box-shadow: none;
  color: rgba(17, 24, 39, 0.36);
}

.pending-action {
  background: rgba(255, 255, 255, 0.76);
  border-radius: 999rpx;
  font-size: 22rpx;
  padding: 8rpx 12rpx;
}

.pending-arrow {
  font-size: 26rpx;
  font-weight: 900;
  margin-right: 4rpx;
}

.badge {
  align-self: flex-start;
  background: rgba(31, 111, 235, 0.1);
  border-radius: 8rpx;
  color: #1f6feb;
  font-size: 22rpx;
  padding: 6rpx 10rpx;
}

.badge.ok {
  background: rgba(31, 111, 235, 0.1);
  color: #1f6feb;
}

.badge.bad {
  background: #fee2e2;
  color: #dc2626;
}

.stem {
  color: #111827;
  font-size: 30rpx;
  font-weight: 700;
  line-height: 1.6;
}

.question-image {
  border-radius: 16rpx;
  margin-top: 8rpx;
  width: 100%;
}

.options {
  gap: 12rpx;
}

.option {
  background: rgba(255, 255, 255, 0.62);
  border: 2rpx solid transparent;
  border-radius: 16rpx;
  display: flex;
  gap: 16rpx;
  padding: 18rpx;
}

.option.chosen {
  border-color: #38577a;
  background: rgba(56, 87, 122, 0.08);
}

.option-key {
  color: #1f6feb;
  font-weight: 700;
}

.option-text {
  color: rgba(17, 24, 39, 0.7);
  flex: 1;
  font-size: 26rpx;
  line-height: 1.55;
}

.submit {
  margin-top: 8rpx;
}

.question-nav {
  align-items: center;
  flex-direction: row;
  gap: 16rpx;
  justify-content: space-between;
}

.nav-btn {
  min-height: 72rpx;
  min-width: 160rpx;
}

.nav-text {
  color: rgba(17, 24, 39, 0.55);
  font-size: 26rpx;
}

.score-card {
  background: #38577a;
  border-radius: 24rpx;
  color: #fff;
  display: flex;
  flex-direction: column;
  gap: 10rpx;
  padding: 42rpx;
  text-align: center;
}

.score {
  font-size: 76rpx;
  font-weight: 800;
}

.score-label {
  color: rgba(255, 255, 255, 0.72);
  font-size: 26rpx;
}
</style>
